import { ToTProcessState } from "./types/tot";

export interface Message {
  id: string;
  role: "user" | "model";
  text: string;
  timestamp: number;
  isError?: boolean;
  thinkingProcess?: ThinkingProcess;
  /** Tree-of-Thought process state (mutually exclusive with thinkingProcess) */
  totProcess?: ToTProcessState;
  /** IDs of artifacts generated in this message */
  artifactIds?: string[];
  /** Summarized context for history (internal use only, generated by summarization service) */
  contextSummary?: string;
}

export interface Artifact {
  id: string;
  type:
    | "tsx"
    | "html"
    | "c"
    | "python"
    | "js"
    | "ts"
    | "sql"
    | "mermaid"
    | "project";
  title: string;
  content: string;
  status: "streaming" | "complete";
  isVisible: boolean;
  timestamp?: number;
}

export interface ThinkingProcess {
  state: "idle" | "diverging" | "critiquing" | "synthesizing" | "complete";
  logs: string[];
  trace: ExecutionStep[];
  hypotheses: Strategy[];
  masterBlueprint?: MasterBlueprint;
}

export interface ExecutionStep {
  id: string;
  phase: "Divergence" | "Critique" | "Synthesis";
  title: string;
  status: "pending" | "running" | "complete" | "failed";
  thoughts?: string;
  result?: any;
  durationMs?: number;
}

export interface Strategy {
  id: string;
  title: string;
  strategy: string;
  assumption: string;
  critique?: {
    strengths?: string[];
    validity_conditions?: string;
    invalidity_triggers: string[];
    critical_flaws: string;
  };
}

export interface MasterBlueprint {
  blueprint: string;
  objective: string;
  tone: string;
  safeguards: string[];
}

export interface ChatSession {
  id: string;
  title: string;
  messages: Message[];
  artifacts: Artifact[]; // Store artifacts per session
  updatedAt: number;
}

export interface ModelConfig {
  model: string;
  temperature: number;
  /** Maximum Tree-of-Thought recursion depth (1-5) */
  maxToTDepth: number;
  /** Force decomposition mode (Deep Mode toggle) */
  forceDeepMode: boolean;
}

// Re-export ToT types for convenience
export * from "./types/tot";

export interface ApiTrace {
  id: string;
  timestamp: number;
  model: string;
  durationMs: number;
}

export interface AppStats {
  flashCount: number;
  proCount: number;
  traces: ApiTrace[];
}

export enum GeminiModel {
  PRO_3_PREVIEW = "gemini-3-pro-preview",
  FLASH_3_PREVIEW = "gemini-3-flash-preview",
}
